---
apiVersion: v1
data:
  ks-config.yaml: |
    ---
    kubernetes:
      apiserverAddr: 8AC15C5B09A372B6A2D2E06E7A5F586F.gr7.us-east-1.eks.amazonaws.com:443      # master addr or master's lb addr

    etcd:
      endpointIps: 8AC15C5B09A372B6A2D2E06E7A5F586F.gr7.us-east-1.eks.amazonaws.com
      port: 2379
      tlsEnable: false

    persistence:
      storageClass: "gp2"

    plugins:
      storage: "openebs-hostpath"    # "csi-qingcloud", "csi-aliyun", "csi-tencentcloud"

    common:
      mysqlVolumeSize: 20Gi
      minioVolumeSize: 20Gi
      etcdVolumeSize: 20Gi
      openldapVolumeSize: 2Gi
      redisVolumSize: 2Gi

    metrics-server:
      enabled: True

    console:
      disableMultiLogin: True  # enable/disable multi login
      port: ""

    monitoring:
      enabled: True
      prometheusReplica: 2
      prometheusMemoryRequest: 400Mi
      prometheusVolumeSize: 20Gi
      grafana:
        enabled: true

    logging:
      enabled: False
      elasticsearchMasterReplica: 1
      elasticsearchDataReplica: 2
      elasticsearchVolumeSize: 20Gi
      logMaxAge: 7
      elkPrefix: logstash
      containersLogMountedPath: ""
      kibana:
        enabled: false
      logsidecarInjector:
        enabled: false

    openpitrix:
      enabled: True

    devops:
      enabled: True
      jenkinsMemoryLim: "8Gi"
      jenkinsMemoryReq: "4Gi"
      jenkinsVolumeSize: "8Gi"
      sonarqube:
        enabled: True

    servicemesh:
      enabled: True

    notification:
      enabled: True

    alerting:
      enabled: True

    harbor:
      enabled: False

    gitlab:
      enabled: False

kind: ConfigMap
metadata:
  name: ks-installer
  namespace: kubesphere-system
